kind: Service
apiVersion: v1
metadata:
  name: ref-quorum-node1
  namespace: jenkins
spec:
  type: ExternalName
  externalName: quorum-node1-rpc.default.svc.cluster.local
  ports:
    - port: 8545


---

kind: Service
apiVersion: v1
metadata:
  name: ref-eth-adapter
  namespace: jenkins
spec:
  type: ExternalName
  externalName: ethadapter-service.default.svc.cluster.local
  ports:
    - port: 3000
