
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-permissioned-config

  labels:
    app: qubernetes
    name: quorum-permissioned-config
data:
  permissioned-nodes.json: |

    [
      "enode://d51fc20f5ce9d6dd45e035471287d079f1c027e7b88328ff7a8e5e26819318078f6f1bbe0cd19d5902367961d32022c3bc3d24d640d3b098419df46000c811a6@quorum-node1:30303?discport=0&raftport=50401",
        "enode://246f5003d339c5adc754137e5084d891e15854f548971c2177a3331ed9911cd03a054111ed0ada7c2f2b9585f4ababb9332fe9f2301100ca326f59035adbf621@quorum-node2:30303?discport=0&raftport=50401",
        "enode://ee82417c7175c053b0dac6e00513ff5afcc2bccc5761d0ee27c4cdbea579f0cdaa4b502bcf79b2d3a43c2999052d9c3f43725220b1b900d3341327fa0a5523d8@quorum-node3:30303?discport=0&raftport=50401"

    ]


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-management

  labels:
    app: qubernetes
    name: node-management
data:
  ibft_propose.sh: |-
    #/bin/ash

    if [ $# -lt 1 ]; then
      echo " An address to vote in, or out, must be provided: "
      echo " ./propose_ibft.sh HEX_ADDRESS (true|false)"
    fi

    ADDRESS=$1
    VOTE_BOOL=true

    if [ $# -eq 2 ]; then
     VOTE_BOOL=$2
    fi
    RES=$(geth --exec "istanbul.propose(\"$1\", $VOTE_BOOL)" attach ipc:$QUORUM_HOME/dd/geth.ipc)
    echo $RES
  ibft_propose_all.sh: |-
    #!/bin/ash
    #set -xe

    for Addr in $( awk '/validators/,0' $QHOME/istanbul-validator-config.toml/istanbul-validator-config.toml | grep "0x" | sed 's/,//g; s/"//g' ); do
      echo $Addr
      $QHOME/node-management/ibft_propose.sh $Addr true
    done
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istanbul-validator-config.toml

  labels:
    app: qubernetes
    name: istanbul-validator-config
data:
  istanbul-validator-config.toml: |-
    vanity = "0x00"
    validators = [
    "0x675C45F552bf204948ABD9AC07eaA2701d373076",
    "0x6876950D912F2Cdc8078c1275C2309e9cdf3466F",
    "0x93698B9825De1Bd22Ef0cB26cbDC00846D2c9Ad4",
    ]

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: geth-helpers

  labels:
    app: qubernetes
    name: geth-helpers
data:
  geth-attach.sh: |-
    #!/bin/sh

    # helper for connecting to geth from
    # outside the container
    # kubectl exec -it $POD -c quorum -- /geth-helpers/geth-attach.sh
    echo "connecting to geth $QHOME"
    geth attach --datadir $QUORUM_DATA_DIR $QUORUM_DATA_DIR/geth.ipc
  geth-exec.sh: |-
    #!/bin/sh

    # helper for connecting to geth from
    # outside the container
    # kubectl exec -it $POD -c quorum -- /geth-helpers/geth-exec.sh "admin.peers.length"

    GETH_CMD="eth.blockNumber"
    if [ "$#" -gt 0 ]; then
      GETH_CMD=$1
    fi
    # see: https://github.com/ethereum/go-ethereum/pull/17281
    # https://github.com/ethereum/go-ethereum/issues/16905
    # to avoid warning being returned
    # "WARN [02-20|00:21:04.382] Sanitizing cache to Go's GC limits  provided=1024 updated=663"
    geth --exec $GETH_CMD  --cache=16 attach --datadir $QUORUM_DATA_DIR $QUORUM_DATA_DIR/geth.ipc
