---
# nodekey private to the node, used to verify identity.
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node1-nodekey-config

  labels:
    app: qubernetes
    name: quorum-node1-nodekey-config
data:
  nodekey: |
    94169e38cc366ef482a038a5389145631eb6fe9849885dc449cad0174153f461
# Only IBFT / istanbul networks need access to the nodekey address.
---
# nodekey address public and used to generate istanbul-validator-config.toml
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node1-nodekey-address-config

  labels:
    app: qubernetes
    name: quorum-node1-nodekey-address-config
data:
  nodekey: |
    0x675C45F552bf204948ABD9AC07eaA2701d373076

---
# enode Id
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node1-enode-config

  labels:
    app: qubernetes
    name: quorum-node1-enode-config
data:
  enode: |
    d51fc20f5ce9d6dd45e035471287d079f1c027e7b88328ff7a8e5e26819318078f6f1bbe0cd19d5902367961d32022c3bc3d24d640d3b098419df46000c811a6

---
# nodekey private to the node, used to verify identity.
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node2-nodekey-config

  labels:
    app: qubernetes
    name: quorum-node2-nodekey-config
data:
  nodekey: |
    b617a3083286bf3df41b75d996b715d78b9739bef835c9c8765c0873079f787d
# Only IBFT / istanbul networks need access to the nodekey address.
---
# nodekey address public and used to generate istanbul-validator-config.toml
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node2-nodekey-address-config

  labels:
    app: qubernetes
    name: quorum-node2-nodekey-address-config
data:
  nodekey: |
    0x6876950D912F2Cdc8078c1275C2309e9cdf3466F

---
# enode Id
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node2-enode-config

  labels:
    app: qubernetes
    name: quorum-node2-enode-config
data:
  enode: |
    246f5003d339c5adc754137e5084d891e15854f548971c2177a3331ed9911cd03a054111ed0ada7c2f2b9585f4ababb9332fe9f2301100ca326f59035adbf621


---
# nodekey private to the node, used to verify identity.
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node3-nodekey-config

  labels:
    app: qubernetes
    name: quorum-node3-nodekey-config
data:
  nodekey: |
    d83c8eb9229dd330a0f17011de673f87acffd3dcc0b3e9a190dbd63e8236f249
# Only IBFT / istanbul networks need access to the nodekey address.
---
# nodekey address public and used to generate istanbul-validator-config.toml
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node3-nodekey-address-config

  labels:
    app: qubernetes
    name: quorum-node3-nodekey-address-config
data:
  nodekey: |
    0x93698B9825De1Bd22Ef0cB26cbDC00846D2c9Ad4

---
# enode Id
apiVersion: v1
kind: ConfigMap
metadata:
  name: quorum-node3-enode-config

  labels:
    app: qubernetes
    name: quorum-node3-enode-config
data:
  enode: |
    ee82417c7175c053b0dac6e00513ff5afcc2bccc5761d0ee27c4cdbea579f0cdaa4b502bcf79b2d3a43c2999052d9c3f43725220b1b900d3341327fa0a5523d8

