apiVersion: apps/v1
kind: Deployment
metadata:
  name: governance-deployment
  labels:
    app: governance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: governance
  template:
    metadata:
      labels:
        app: governance
    spec:
      containers:
        - image: mabdockerid/pharma-gov:latest
          imagePullPolicy: Always
          name: governance
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
